### ISSUE TITLE
Syntax ERROR

### ISSUE THREAD

**Issue by Abdulsamipy** [supmanyu/InstaScraper#2]
HI, so im trying to run the scraper and getting the following error, does anyone know how to fix it 

`File "C:\Users\\\InstaScraper-masterh\release\Scraper.py", line 71
    print listToString(row), decodeEmail(decode)
          ^
SyntaxError: invalid syntax`

**Comment by axelabbas** [comment]
Make sure to use python2, not python3, that should fix it.
