### ISSUE TITLE
The website have been removed

### ISSUE THREAD

**Issue by axelabbas** [supmanyu/InstaScraper#8]
This tool should not work anymore since the website (theinstaprofile) has been deleted/disabled.

**Comment by supmanyu** [comment]
right, havent got time to work on this due to my job, It would be great if you come across another such service that can be used as a starting point for updating the scraper.

**Comment by axelabbas** [comment]
I understand, and about finding any other site, well I wasn't lucky with that but I found a library that uses instagram endpoint to scrape user info including emails, so I've been working with that trying my best to find a way to use it with no rate limits or ip block, still researching though so who knows
Thats the library https://github.com/megadose/toutatis
